comics=[
    {
        avatar:"../avatar/onepice.jpg",
        name: "One Pice",
        othername:"Vua Hải Tặc; Đảo Hải Tặc; OnePiece",
        author:"Eiichiro Oda",
        status:"Đang cập nhật",
        category:"Action,Adventure,Comedy,Drama,Fantasy,Shounen,Supernatural",
        intro:"One Piece là câu truyện kể về Luffy và các thuyền viên của mình. Khi còn nhỏ, Luffy ước mơ trở thành Vua Hải Tặc. Cuộc sống của cậu bé thay đổi khi cậu vô tình có được sức mạnh có thể co dãn như cao su, nhưng đổi lại, cậu không bao giờ có thể bơi được nữa. Giờ đây, Luffy cùng những người bạn hải tặc của mình ra khơi tìm kiếm kho báu One Piece, kho báu vĩ đại nhất trên thế giới. Trong One Piece, mỗi nhân vật trong đều mang một nét cá tính đặc sắc kết hợp cùng các tình huống kịch tính, lối dẫn truyện hấp dẫn chứa đầy các bước ngoặt bất ngờ và cũng vô cùng hài hước đã biến One Piece trở thành một trong những bộ truyện nổi tiếng nhất không thể bỏ qua. Hãy đọc One Piece để hòa mình vào một thế giới của những hải tặc rộng lớn, đầy màu sắc, sống động và thú vị, cùng đắm chìm với những nhân vật yêu tự do, trên hành trình đi tìm ước mơ của mình.",
        likes:65197,
        follows:159297,
        views:355836496,
        chapnumber:1063,
        type_label:"new",
        time_ago:"3 giờ trước",
        link:"https://truyenqqpro.com/truyen-tranh/one-piece-128"
    },
    {
        avatar:"../avatar/Thần Chết Ichigo.jpg",
        name: "Thần Chết Ichigo",
        othername:"Bleach; Sứ Giả Thần Chết",
        author:"Tite Kubo",
        status:"Đang cập nhật",
        category:"Action,Adventure,Comedy,Drama,Fantasy,Shounen,Supernatural",
        intro:"Nhân vật chính của Bleach là Ichigo Kurosaki có khả năng nhìn thấy những hồn ma. Cuộc sống của cậu thay đổi khi cậu gặp Rukia Kuchiki, một Thần Chết và là thành viên của Âm Giới. Khi chiến đấu với một yêu quái chuyên đi săn những người có năng lực tâm linh, Rukia đã cho Ichigo mượn sức mạnh của mình để cậu có thể cứu gia đình mình. Nhưng trước sự ngạc nhiên của Rukia, Ichigo đã hấp thu toàn bộ sức mạnh của cô. Khi đã trở thành một Thần Chết, Ichigo nhanh chóng biết được rằng thế giới cậu đang sống chứa đầy những linh hồn nguy hiểm, và cùng với Rukia, người đang từ từ khôi phục lại sức mạnh của mình, công việc của Ichigo lúc này là bảo vệ những người vô tội khỏi lũ yêu quái và giúp đỡ những linh hồn tìm được nơi yên nghỉ. Không dừng lại tại đó, trong Bleach, Ichigo sẽ dần phải đụng độ với các tổ chức hùng mạnh, với những âm mưu đan xen để bảo vệ thế giới. Mỗi phần của truyện đều có liên kết chặt chẽ với nhau chứ không tách rời. Đọc Bleach, bạn khó có thể dừng theo dõi các trận chiến hoành tráng và hấp dẫn nối tiếp nhau.",
        likes:1882,
        follows:9426,
        views:31091761,
        chapnumber:686,
        type_label:"hot",
        time_ago:"4 giờ trước",
        link:"https://truyenqqpro.com/truyen-tranh/than-chet-ichigo-141"
    },
    {
        avatar:"../avatar/Âm Thanh Của Bầu Trời.jpg",
        name: "Âm Thanh Của Bầu Trời",
        othername:"Welkinwhistle: The Sound Of The Skies; Hisakata No Oto",
        author:"Ishii Asuka",
        status:"Đang cập nhật",
        category:"Fantasy,Mystery,Slice Of Life",
        intro:"Tatsumi đã nhanh chóng chấp nhận một công việc mới - làm giáo viên trên một hòn đảo nhỏ xung quanh Quần đảo Ogasawara tên là 'Aoshima', nơi anh gặp phải những hiện tượng khó lường mà bất chấp mọi logic. Câu chuyện tưởng tượng ấm áp này là gợi lên sự bí ẩn và kì diệu của tự nhiên. Nhưng đây là một hòn đảo xanh đầy mê hoặc đang chào đón anh ấy, hay còn ẩn chứa một điều gì khác? Hòn đảo kêu gọi bạn, đưa bạn vào một thế giới siêu giác quan. Hãy tận hưởng chút phép màu này nhé.",
        likes:2,
        follows:35,
        views:2986,
        chapnumber:10,
        type_label:"",
        time_ago:"8 giờ trước",
        link:"https://truyenqqpro.com/truyen-tranh/am-thanh-cua-bau-troi-13127"
    },
    {
        avatar:"../avatar/Adelia Của Tôi.jpg",
        name: "Adelia Của Tôi",
        othername:"Boku No Adelia, My Adelia",
        author:"Đang Cập Nhật",
        status:"Đang cập nhật",
        category:"Comedy,Supernatural,Slice Of Life",
        intro:"Sau khi chạy trốn khỏi ngôi làng bị ma cà rồng phá hủy, cậu bé người sói Joel đã bị ngất và được một phụ nữ tên Adelia đưa về nhà chăm sóc.",
        likes:20,
        follows:141,
        views:"16969",
        chapnumber:27,
        type_label:"",
        time_ago:"1 ngày trước",
        link:"https://truyenqqpro.com/truyen-tranh/adelia-cua-toi-12952"
    },
    {
        avatar:"../avatar/Kingdom – Vương Giả Thiên Hạ.jpg",
        name: "Kingdom – Vương Giả Thiên Hạ",
        othername:"Kingdom; Kingdom - Vương Giả Thiên Hạ",
        author:"Hara Yasuhisa",
        status:"Đang cập nhật",
        category:"Action,Drama,Martial Arts",
        intro:"Trải qua hàng triệu năm kể từ thời đại của các vị thần. Đây là thời mà khát vọng của một người có thể xoay chuyển cả thế giới. Thời đại của hơn 500 năm binh biến: thời Chiến Quốc. Kingdom – Vương Giả Thiên Hạ là câu chuyển kể về một thiếu niên tên Tín cùng những thử thách cam go, những trận chiến đẫm máu mà cậu cần vượt qua để có thể trở thành một vị tướng quân vĩ đại. Tác phẩm đã giành được giải thưởng văn hóa Tezuka Osamu lần thứ 17 vào năm 2013.",
        likes:4959,
        follows:17109,
        views:39987669,
        chapnumber:734,
        type_label:"hot",
        time_ago:"11 giờ trước",
        link:"https://truyenqqpro.com/truyen-tranh/vuong-gia-thien-ha-245"
    },
    {
        avatar:"../avatar/Tôi Viết Sách Để Thăng Cấp.jpg",
        name:"Tôi Viết Sách Để Thăng Cấp",
        othername:"Đang Cập Nhật",
        author:"Đang Cập Nhật",
        status:"Đang Cập Nhật",
        category:"Action,School Life,Manhwa,Truyện Màu",
        intro:"Truyện tranh Tôi Viết Sách Để Thăng Cấp được cập nhật nhanh và đầy đủ nhất tại TruyenQQ. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ TruyenQQ ra các chương mới nhất của truyện Tôi Viết Sách Để Thăng Cấp.",
        likes:1370,
        follows:5563,
        views:1747512,
        chapnumber:131,
        type_label:"new",
        time_ago:"7 giờ trước",
        link:"https://truyenqqpro.com/truyen-tranh/toi-viet-sach-de-thang-cap-10492"
    },
    {
        avatar:"../avatar/Thám Tử Conan.jpg",
        name:"Thám Tử Conan",
        othername:"Conan",
        author:"Aoyama Gōshō",
        status:"Đang Cập Nhật",
        category:"Adventure,Comedy,Drama,Fantasy,Shounen",
        intro:"Nhân vật chính của truyện là một thám tử học sinh trung học có tên là Kudo Shinichi, người đã bị biến thành một cậu bé cỡ học sinh tiểu học và luôn cố gắng truy tìm tung tích tổ chức Áo Đen nhằm lấy lại hình dáng cũ.",
        likes:4009,
        follows:16202,
        views:17902948,
        chapnumber:1101,
        type_label:"new",
        time_ago:"15 phút trước",
        link:"https://truyenqqpro.com/truyen-tranh/tham-tu-conan-199"
    },
]
